env:
  es6: true
  node: true
extends: 'eslint:recommended'
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  comma-spacing:
    - error
    - before: false
      after: true
  array-bracket-spacing:
    - error
    - never
  no-multi-spaces:
    - error
  key-spacing:
    - error
    - beforeColon: false
      afterColon: true
  space-infix-ops:
    - error
  strict:
    - error
    - global
  curly:
    - error
